name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: githubaction
      USER_EMAIL: githubaction@fake.com
      PUBLISH_DIR: ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: wowdacom
      - name: Use Node.js ${{ matrix.node-version }}
        uses: wowdacom
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run gulp m
          npm run build
      - name: Commit files
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.name wowdacom
          git config --local user.email wowdacom@gmail.com
          git status
          git remote add origin https://github.com/wowdacom/TechNotes.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy to Github pages"
          git push origin gh-pages -f
